title: QuanTAS 
subtitle: Understanding the limits of Quantum Theory, Algorithms and Systems
logo: /assets/img/QuanTAS_logo.png
description: Supported by Ken Kennedy Institute (Rice University)
show_downloads: true
google_analytics:
theme: jekyll-theme-minimal
