title: CrysFormer 
subtitle: Pushing the frontiers of Structural Biology + AI
logo: /assets/img/crysformer_logo.png
description: Supported by the Welch Foundation Grant A22-0307
show_downloads: true
google_analytics:
theme: jekyll-theme-minimal
